import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'

import { GiphyFetch } from '@giphy/js-fetch-api'
import Button from '../components/Button';
import GIF from '../components/GIF';
import Grid from '../components/Grid';
import SearchBar from '../components/SearchBar';


export default function Home() {
  const [buttonText, setButtonText] = useState("GIF");
  const [buttonState, setButtonState] = useState(true);
  const [searchState, setSearchState] = useState(false);
  const [searchContent, setSearchContent] = useState("OMG");
  const [gifs, setGifs] = useState<any | null>(null);
  const [selectedGIF, setSelectedGIF] = useState<any | null>(null);

  const gf = new GiphyFetch(process.env.GIPHY_API_KEY as string)

  const fetchGifs = async () => {
    return await gf.search(searchContent, { sort: 'relevant', limit: 12 }).then(result => {
      return result.data.map((e, i) => { return <GIF src={e.images.original.url} key={i} /> });
    })
  }
  useEffect(()=>{
    // fetchGifs().then(d => setGifs(d));
  },[gifs]);

  const handleSearchContent = async(content: string) => {
    setSearchContent(content);
    let data = await fetchGifs();
    console.log(data);
    // setGifs(data);
  };

  const handleGIFClick = (event: any) => {
    setSearchState(false)
    let selectedGIF = <GIF src={event.target.currentSrc} key={1} />
    setSelectedGIF(selectedGIF)
    setGifs([])
  };

  const handleButtonClick = () => {
    if (buttonState) {
      setSearchState(true)
      setSelectedGIF(null)
      setButtonText("X");
      setButtonState(!buttonState)
    }
    else {
      setSearchState(false)
      setButtonText("GIF");
      setSelectedGIF(null)
      setButtonState(!buttonState)
    }
  }
  return (
    <>
      <Head>
        <title>Giphy Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {searchState && <SearchBar onChange={handleSearchContent} />}
        {selectedGIF ? selectedGIF : <Grid gifs={gifs} onClick={handleGIFClick} />}
        <Button state={buttonState} text={buttonText} onClick={handleButtonClick} />

      </main>
    </>
  )

}
