import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from "react";


const inter = Inter({ subsets: ['latin'] })
// import { Grid } from '@giphy/react-components'
import { GiphyFetch } from '@giphy/js-fetch-api'
import Button from '../components/Button';
import GIF from '../components/Gif';
import Grid from '../components/Grid';
import SearchBar from '../components/SearchBar';

const viewStates = ['initial', 'search', 'grid', 'detail'];

export default function Home() {

  const gf = new GiphyFetch(process.env.GIPHY_API_KEY as string)

  // const fetchGifs = (offset: number) => gf.search("omg", { offset, limit: 12 })
  const [screenState, setScreenState] = useState(viewStates[0]);
  const [buttonState, setButtonState] = useState("GIF");

  let gifs = []

  for (let i = 0; i < 10; i++) {
    gifs.push(<GIF src={'https://source.unsplash.com/random' + '/' + i} key={i} />)
  }

  return (
    <>
      <Head>
        <title>Giphy Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Grid width={1400} columns={3} fetchGifs={fetchGifs} /> */}

      <main className={styles.main}>
        <SearchBar content='omg' />
        <Grid gifs={gifs} />
        <Button state={buttonState} />
      </main>
    </>
  )
}
